/**
 * Backtest data loaders — reads from SQLite warehouse first, falls back to
 * locally pre-fetched JSON files if warehouse is unavailable or ticker missing.
 * Files are generated by running: node scripts/fetchBacktestData.mjs
 * No external API calls — works in any environment (local, Vercel, sandbox).
 */

import { readFileSync, existsSync, readdirSync } from 'fs'
import { join } from 'path'
import type { OhlcBar } from '@/lib/quant/technicals'
import { getCandles, isWarehouseAvailable, warehouseTickers } from '@/lib/data/warehouse'

export interface OhlcvRow extends OhlcBar {
  time: number // Unix seconds
  volume: number
}

export interface DataFile {
  ticker: string
  sector: string
  fetchedAt: string
  candles: OhlcvRow[]
}

// Path to the pre-fetched data directory (relative to project root)
function dataDir(): string {
  return join(process.cwd(), 'scripts', 'backtestData')
}

/**
 * Read a pre-fetched JSON data file for a given ticker.
 * Returns null if file doesn't exist (ticker not pre-fetched yet).
 */
export function loadLocalData(ticker: string): DataFile | null {
  const safe = ticker.replace(/\./g, '-')  // BRK.B → BRK-B
  const filePath = join(dataDir(), `${safe}.json`)
  if (!existsSync(filePath)) return null
  try {
    const raw = readFileSync(filePath, 'utf-8')
    return JSON.parse(raw) as DataFile
  } catch {
    return null
  }
}

/**
 * Load daily OHLCV history for a stock ticker.
 * Priority: SQLite warehouse → local JSON file.
 * Returns empty array if data not found in either source.
 */
export function loadStockHistory(ticker: string): OhlcvRow[] {
  // Try warehouse first
  if (isWarehouseAvailable()) {
    const bars = getCandles(ticker)
    if (bars && bars.length > 0) {
      return bars.map((b) => ({
        time: Math.floor(new Date(b.date).getTime() / 1000),
        open: b.open,
        high: b.high,
        low: b.low,
        close: b.close,
        volume: b.volume,
      }))
    }
  }

  // Fallback to JSON
  const data = loadLocalData(ticker)
  if (!data) return []
  const out: OhlcvRow[] = []
  for (const c of data.candles) {
    if (
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close)
    ) {
      out.push({ time: c.time, open: c.open, high: c.high, low: c.low, close: c.close, volume: c.volume ?? 0 })
    }
  }
  return out
}

/**
 * Load daily BTC/USD OHLCV from pre-fetched local JSON.
 * Returns empty array if data file not found.
 */
export function loadBtcHistory(): OhlcvRow[] {
  const data = loadLocalData('BTC')
  if (!data) return []
  const out: OhlcvRow[] = []
  for (const c of data.candles) {
    if (
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close)
    ) {
      out.push({ time: c.time, open: c.open, high: c.high, low: c.low, close: c.close, volume: c.volume ?? 0 })
    }
  }
  return out
}

/**
 * Get the list of all tickers that have pre-fetched data.
 * Returns union of warehouse tickers and JSON file tickers.
 */
export function availableTickers(): string[] {
  const warehouseSet = new Set(isWarehouseAvailable() ? warehouseTickers() : [])

  const dir = dataDir()
  if (existsSync(dir)) {
    for (const f of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
      warehouseSet.add(f.replace(/\.json$/, '').replace(/-/g, '.'))  // BRK-B → BRK.B
    }
  }

  return Array.from(warehouseSet).sort()
}

/** Convert OhlcvRow[] to close price array. */
export function closesFromRows(rows: OhlcvRow[]): number[] {
  return rows.map((r) => r.close)
}

/** Convert OhlcvRow[] to OhlcBar[] (strip time/volume). */
export function barsFromRows(rows: OhlcvRow[]): OhlcBar[] {
  return rows.map(({ open, high, low, close }) => ({ open, high, low, close }))
}
