/**
 * Backtest data loaders — reads from locally pre-fetched JSON files.
 * Same interface as lib/backtest/dataLoader.ts but for use in scripts.
 * Files generated by: node scripts/fetchBacktestData.mjs
 */

import { readFileSync, existsSync, readdirSync } from 'fs'
import { join } from 'path'

export interface OhlcvRow {
  time: number // Unix seconds
  open: number
  high: number
  low: number
  close: number
  volume: number | undefined
}

export interface DataFile {
  ticker: string
  sector: string
  fetchedAt: string
  candles: OhlcvRow[]
}

function dataDir(): string {
  return join(process.cwd(), 'scripts', 'backtestData')
}

export function loadLocalData(ticker: string): DataFile | null {
  const safe = ticker.replace(/\./g, '-')
  const filePath = join(dataDir(), `${safe}.json`)
  if (!existsSync(filePath)) return null
  try {
    return JSON.parse(readFileSync(filePath, 'utf-8')) as DataFile
  } catch {
    return null
  }
}

export function loadStockHistory(ticker: string): OhlcvRow[] {
  const data = loadLocalData(ticker)
  if (!data) return []
  return data.candles.filter(
    (c) =>
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close),
  )
}

export function loadBtcHistory(): OhlcvRow[] {
  const data = loadLocalData('BTC')
  if (!data) return []
  return data.candles.filter(
    (c) =>
      Number.isFinite(c.time) &&
      Number.isFinite(c.open) &&
      Number.isFinite(c.high) &&
      Number.isFinite(c.low) &&
      Number.isFinite(c.close),
  )
}

export function closesFromRows(rows: OhlcvRow[]): number[] {
  return rows.map((r) => r.close)
}

export function barsFromRows(rows: OhlcvRow[]): { open: number; high: number; low: number; close: number }[] {
  return rows.map(({ open, high, low, close }) => ({ open, high, low, close }))
}
